

ALTER TABLE `book`
  CHANGE COLUMN `idbook` `idbook` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ADD COLUMN `creativeWork` INT UNSIGNED NOT NULL AFTER `idbook`,
  ADD COLUMN `thing` INT UNSIGNED DEFAULT NULL AFTER `idbook`,
  ADD COLUMN `bookFormat` VARCHAR(20) NULL AFTER `idbook`,
  ADD COLUMN `illustrator` INT UNSIGNED NULL AFTER `idbook`,
  ADD COLUMN `isbn` VARCHAR(18) NULL AFTER `idbook`,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`idbook`);

ALTER TABLE `contactPoint`
  CHANGE COLUMN `idcontactPoint` `idcontactPoint` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ADD COLUMN `thing` INT UNSIGNED DEFAULT NULL AFTER `idcontactPoint`,
  ADD COLUMN `contactOption` VARCHAR(100) DEFAULT NULL AFTER `idcontactPoint`,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`idcontactPoint`);

ALTER TABLE `event`
  DROP COLUMN `additionalType`,
  CHANGE COLUMN `idevent` `idevent` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `superEvent` `superEvent` INT UNSIGNED DEFAULT NULL,
  CHANGE COLUMN `organizerId` `organizer` INT UNSIGNED DEFAULT NULL,
  ADD COLUMN `thing` INT UNSIGNED DEFAULT NULL AFTER `idevent`,
  ADD COLUMN `about` INT UNSIGNED DEFAULT NULL AFTER `idevent`,
  ADD COLUMN `director` VARCHAR(255) DEFAULT NULL AFTER `idevent`,
  ADD COLUMN `keywords` VARCHAR(255) DEFAULT NULL AFTER `idevent`,
  ADD COLUMN `subEvent` INT UNSIGNED DEFAULT NULL AFTER `idevent`,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`idevent`);


ALTER TABLE `invoice`
  CHANGE COLUMN `idinvoice` `idinvoice` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ADD COLUMN `thing` INT UNSIGNED DEFAULT NULL AFTER `idinvoice`,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`idinvoice`);

ALTER TABLE `localBusiness`
  ADD COLUMN `thing` INT UNSIGNED DEFAULT NULL AFTER `idlocalbusiness`,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`idlocalBusiness`);

ALTER TABLE `offer`
  CHANGE COLUMN `idoffer` `idoffer` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ADD COLUMN `thing` INT UNSIGNED DEFAULT NULL AFTER `idoffer`,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`idoffer`);

ALTER TABLE `order`
  CHANGE COLUMN `idorder` `idorder` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ADD COLUMN `thing` INT UNSIGNED DEFAULT NULL AFTER `idorder`,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`idorder`);

ALTER TABLE `orderItem`
  CHANGE COLUMN `idorderItem` `idorderItem` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ADD COLUMN `thing` INT UNSIGNED NOT NULL AFTER `idorderItem`,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`idorderItem`);

ALTER TABLE `organization`
  DROP COLUMN `additionalType`,
  CHANGE COLUMN `idorganization` `idorganization` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `areaServed` `areaServed` INT UNSIGNED DEFAULT NULL,
  CHANGE COLUMN `location` `location` INT UNSIGNED DEFAULT NULL,
  ADD COLUMN `thing` INT UNSIGNED NOT NULL AFTER `idorganization`,
  ADD COLUMN `logo` INT UNSIGNED DEFAULT NULL AFTER `idorganization`,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`idorganization`);

ALTER TABLE `person`
  CHANGE COLUMN `idperson` `idperson` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ADD COLUMN `thing` INT UNSIGNED NOT NULL AFTER `idperson`,
  ADD COLUMN `deathDate` DATE DEFAULT NULL AFTER `gender`,
  ADD COLUMN `deathPlace` VARCHAR(45) DEFAULT NULL AFTER `gender`,
  ADD COLUMN `homeLocation` INT UNSIGNED NULL,
  ADD COLUMN `memberOf` INT UNSIGNED NULL,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`idperson`);

ALTER TABLE `place`
  CHANGE COLUMN `idplace` `idplace` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  CHANGE COLUMN `address` `address` INT UNSIGNED DEFAULT NULL,
  ADD COLUMN `thing` INT UNSIGNED NOT NULL AFTER `idplace`,
  ADD COLUMN `publicAccess` TINYINT DEFAULT 0,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`idplace`);

ALTER TABLE `postalAddress`
  CHANGE COLUMN `idpostalAddress` `idpostalAddress` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ADD COLUMN `thing` INT UNSIGNED NOT NULL AFTER `idpostalAddress`,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`idpostalAddress`) ;

ALTER TABLE `product`
  CHANGE COLUMN `idproduct` `idproduct` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ADD COLUMN `thing` INT UNSIGNED NOT NULL AFTER `idproduct`,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`idproduct`);

ALTER TABLE `service`
  CHANGE COLUMN `idservice` `idservice` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ADD COLUMN `thing` INT UNSIGNED NOT NULL AFTER `idservice`,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`idservice`);

ALTER TABLE `taxon`
  CHANGE COLUMN `idtaxon` `idtaxon` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ADD COLUMN `thing` INT UNSIGNED NOT NULL AFTER `idtaxon`,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`idtaxon`);

ALTER TABLE `videoObject`
  CHANGE COLUMN `idvideoObject` `idvideoObject` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ADD COLUMN `creativeWork` INT UNSIGNED NOT NULL AFTER `idvideoObject`,
  ADD COLUMN `thing` INT UNSIGNED DEFAULT NULL AFTER `idvideoObject`,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`idvideoObject`),
  ENGINE = InnoDB ;

ALTER TABLE `webPage`
  CHANGE COLUMN `idwebPage` `idwebPage` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ADD COLUMN `thing` INT UNSIGNED NOT NULL AFTER `idwebPage`,
  ADD COLUMN `creativeWork` INT UNSIGNED NOT NULL AFTER `idwebPage`,
  ADD COLUMN `primaryImageOfPage` INT UNSIGNED DEFAULT NULL,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`idwebPage`);

ALTER TABLE `webPageElement`
  CHANGE COLUMN `idwebPageElement` `idwebPageElement` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ADD COLUMN `thing` INT UNSIGNED NOT NULL AFTER `idwebPageElement`,
  ADD COLUMN `creativeWork` INT UNSIGNED NOT NULL AFTER `idwebPageElement`,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`idwebPageElement`);

ALTER TABLE `webSite`
  CHANGE COLUMN `idwebSite` `idwebSite` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ADD COLUMN `thing` INT UNSIGNED NOT NULL AFTER `idwebSite`,
  ADD COLUMN `creativeWork` INT UNSIGNED NOT NULL AFTER `idwebSite`,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`idwebSite`);
